### ISSUE TITLE
Solved: LICENSE about fork and publish

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [tako774/tsk_report#2]
Let me do introduction first: 
I'm a hisoutensoku player from China. This is my page on tenco website
http://tenco.info/game/2/account/2BEmperor/
I saw tenco project has running 7 yeas. In China, our gamer group meet a big problem,
and I hope I can resolve the problem through tenco.

As you can see I find my friend and created a Chinese version of tsk_report,
and successful bring them into tsk_report program source code.

Now I want to know if I must be publish my binaries as a single zip archive include all files,
What kind of extra information should I pack at the same time?
Maybe we often call them "LICENSE" on github.

For myself, these translate woks may publish as "MIT" or "WTFPL"
but I still not learn what kind of license does tsk_report has.

In addition, I meet some problem during my tsk_report programming, I don't understand RUBY.
I may open multiple issue to talk about them, you're author of tsk_report, I think you'll know the best.

Thanks again for your amazing tenco software.

**Comment by tako774** [comment]
I answer about tsk_report licence.

It is written in readme in Japanese. Roughly in English, "copying, redistributing, and modifying is free at your own risk". So you can redistribute your translated version at free.

One thing to mind, if you include ruby interpreter in distributions as like original tsk_report, you must show how to get ruby source code. Please read the Ruby license.
https://www.ruby-lang.org/en/about/license.txt (Especially No.3).

```
○ライセンスについて
複製自由・再配布自由・改変自由

ただし、実行ファイルには Rubyインタプリタが含まれます。
これにはRubyライセンスが適用されるため、配布時には下記のいずれかが必要です。
（詳細はRubyライセンスを参照ください）

* Rubyインタプリタのソースコードの入手先をドキュメント等に記載する。
* Rubyインタプリタのソースコードを同梱する。

本プログラムもRubyライセンスに従い、ソースコードの入手先を示します。

オブジェクト指向スクリプト言語 Ruby
http://www.ruby-lang.org/ja/
```

**Comment by Incubator85653** [comment]
For now I am using "ocra" to pack tsk report as single execute file.

There is a problem, Asian(CJK) characters are not support in temp file path.
This often occurs in someone using a Windows system user name that include CJK characters.

Can be check it for a command,
"echo %TMP%"
"echo %TEMP%"

If the returned strings contain CJK characters like Japanese "C:\Users\まどか\Appdata\" or Chinese"C:\Users\姜晓妍\Appdata\"

Program will be failed to execute.

I'm not see this problem occurs on original tsk_teport.
You told me how to pack for another method on Twitter, I'll give it a try soon.

**Comment by mhtvsSFrpHdE** [comment]
Thank you for suggestions about license information.
