### ISSUE TITLE
Solved: How to modify HTTP_REQUEST_HEADER

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [tako774/tsk_report#3]
```
Removed
```

**Comment by tako774** [comment]
I have tried to serve with HTTPS with "let's encrypt" from around 2016 March. So maybe you can connect with HTTPS, but you should modify tsk_report to do so.

And why server causes that error is maybe the request HTTP header hostname field value is not "tenco.info". Could you check the request header?

**Comment by mhtvsSFrpHdE** [comment]
I add these code try to load port information from "env.yaml":

```
SERVER_TRACK_RECORD_PORT = env['server']['track_record']['port'].to_s
SERVER_LAST_TRACK_RECORD_PORT = env['server']['last_track_record']['port'].to_s
SERVER_ACCOUNT_PORT = env['server']['account']['port'].to_s
CLIENT_LATEST_VERSION_PORT = env['client']['latest_version']['port'].to_s
```

Then modify method "get_latest_version":

```
 def get_latest_version(latest_version_host, latest_version_port, latest_version_path)
    response = nil
    Net::HTTP.new(latest_version_host, latest_version_port).start do |s|
      response = s.get(latest_version_path, HTTP_REQUEST_HEADER)
    end  
    response.code == '200' ? response.body.strip : nil
  end
```

I am trying add new variable "port" to each request.
Use as:

```
begin
    latest_version = get_latest_version(CLIENT_LATEST_VERSION_HOST, CLIENT_LATEST_VERSION_PORT, CLIENT_LATEST_VERSION_PATH)
```

I'm successful load port information from "env.yaml" and send request to
"127.0.0.1:26420". (I modified "env.yaml", change "tenco.info" to "127.0.0.1")

I guess that's why program will got "domain error".
Because this equal directly access "tenco.info"'s address but not domain.
I just forward "tenco.info:80" to local "127.0.0.1:26420",
That's why domain was missing, I guess.

**Comment by tako774** [comment]
- Aren't there the ways for clients in China to connect the web server from HongKong or Singapore transparently? I don't how obfs4 works, but in your environment it currently works like a L4 DNAT routing and packet obfuscating server. Could not it run as a socket proxy?
- To add HTTP header field, edit `HTTP_REQUEST_HEADER` hash.

```
HTTP_REQUEST_HEADER = {"User-Agent" => "Tensokukan Report Tool #{PROGRAM_VERSION}"}
```

```
    Net::HTTP.new(latest_version_host, 80).start do |s|
      response = s.get(latest_version_path, HTTP_REQUEST_HEADER)
end 
```
- Please notice there are two domains, one is `static.tenco.info` which serves static contents, the other is `tenco.info` which serves dynamic contents. These are different servers and have different global IP addresses.  So if you add host field to HTTP header, adjust the value for the domain you want to connect. 
- cf. 「ドメインウェブの設定が見つかりません」is only replied from `static.tenco.info`.

**Comment by mhtvsSFrpHdE** [comment]
@tako774 I'll try to learn more information about HTTP header.
I just think, "HTTP_REQUEST_HEADER", it's a string variable, but, how should I modify it?
There isn't an domain information in this string variable, should I add manually? Then how?
Like this?

```
HTTP_REQUEST_HEADER = {tenco.info "User-Agent" => "Tensokukan Report Tool #{PROGRAM_VERSION}"}
```

Oh this is crazy, 
OK maybe I ask too more...

We don't use fully socks5 proxy because this will case abuse.
(Some one may use it to watch youtube videos and we won't let them do it.)
So we directly forward port, and lost the domain header I think.

This is a great tip, we will try it.
If there is anything else we want to know, I will submit them to GitHub issues.

**Comment by mhtvsSFrpHdE** [comment]
```
Removed
```

**Comment by tako774** [comment]
Thanks for your explanation about obfs4 and Chinese environment.

If you want to become responsible for the Chinese version of tsk_report, I think you should understand the coding at least the parts edited from original version. Frankly speaking, `Hash` is very basic programming knowledge not limited to ruby, so you can investigate and learn it...  maybe.

**Comment by Incubator85653** [comment]
Great, I should start it right now.
If there anything else information we want you to know, 
(They may include our forward server IP address, etc. You may find,
many people upload their data over same IP address, this is safe.)
I will put them through GitHub issue,
then send a tweet to @tako774 for rarely checked emails.

O ya su mi!

**Comment by mhtvsSFrpHdE** [comment]
@tako774 my fault... When I realized that variable is a "Hash", I used the fastest speed to achieve this functionality and my codes working.

Sorry to bother you many times, I'm a fool completely.
