### ISSUE TITLE
Solved: Build ruby script to exe, exerb, rubygems LoadError

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [tako774/tsk_report#7]
exerb version 5.4.0
ruby version 1.8.7 (2013-06-27 patchlevel 374) [i386-mingw32]
```
exerb tsk_report.rb
```
Then I got a file "tsk_report.exe".
After execute it, shows
```
tsk_report.rb:3:in `require': No such file to load -- rubygems (LoadError)
        from tsk_report.rb:3
```

What was that? How to create a exe use exerb?
I remember that tsk_report 0.04 published with exerb.

**Comment by tako774** [comment]
I have not got such message and I have no idea now.

I make .exe file with "make_exe.bat" in the repository.

ex. skr_report
```bat
start /wait mkexy skr_report.rb
type skr_report.exy.icon.txt >> skr_report.exy
@pause
exerb skr_report.exy 
```

"mkexy" outputs .exy file. This file contains the full paths of libraries to be included to  the .exe file. It can be the clue for this problem...

**Comment by mhtvsSFrpHdE** [comment]
Thanks. It was successed.
